version: '1.0.0'

services:
  test-server:
    build: 
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=test
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/noted-dev
    # env_file:
    #   - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    networks:
      - backend

  mongo:
    container_name: mongo
    image: mongo:latest
    ports: 
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

volumes:
    mongo-data: {}

networks:
  backend:
    driver: bridge