# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Staging

on:
  push:
    branches: [ "development", "main" ]
  pull_request:
    branches: [ "development", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Chekcout code
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          touch .env
          echo ACCESS_SECRET_KEY="${{ secrets.ACCESS_SECRET_KEY }}" >> .env
          echo ACCESS_EXPIRATION="${{ secrets.ACCESS_EXPIRATION }}" >> .env
          echo REFRESH_SECRET_KEY="${{ secrets.REFRESH_SECRET_KEY }}" >> .env
          echo REFRESH_EXPIRATION="${{ secrets.REFRESH_EXPIRATION }}" >> .env
        shell: bash

      - name: Build & run tests
        run: |
          npm run test:start
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "Tests passed!"
            npm run test:stop
          else
            echo "Tests failed."
            exit 1
          fi


      # - name: Cleanup
      #   run: npm run test:stop
