name: Test

on:
  push:
    branches: [ "development", "main" ]
  pull_request:
    branches: [ "development", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Chekcout code
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          touch .env
          echo ACCESS_SECRET_KEY="${{ secrets.ACCESS_SECRET_KEY }}" >> .env
          echo ACCESS_EXPIRATION="${{ secrets.ACCESS_EXPIRATION }}" >> .env
          echo REFRESH_SECRET_KEY="${{ secrets.REFRESH_SECRET_KEY }}" >> .env
          echo REFRESH_EXPIRATION="${{ secrets.REFRESH_EXPIRATION }}" >> .env
        shell: bash

      - name: Build docker containers & run tests
        run: |
          # npm run test:start
          docker compose -f docker-compose.test.yml up --exit-code-from test-server
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "Tests passed!"
          else
            echo "Tests failed!"
            exit 1
          fi
